"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import type { Person, Project } from "./directory-domain";
import type { WorkItem, WorkItemStatus, WorkflowStage } from "./work-item-domain";

type View = "tree" | "backlog";
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { "content-type": "application/json", ...init?.headers } }); const data = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(data.error ?? "Не удалось выполнить запрос"); return data; }
const stages: Array<[WorkflowStage, string]> = [["backlog","Backlog"],["product","Product"],["design","Design"],["pbr","PBR"],["engineering","Engineering"]];

export default function WorkItemsClient() {
  const [items, setItems] = useState<WorkItem[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [people, setPeople] = useState<Person[]>([]);
  const [view, setView] = useState<View>("tree"); const [projectId, setProjectId] = useState(""); const [defaultProjectId, setDefaultProjectId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const [editing, setEditing] = useState<WorkItem | null>(null); const [parentForNew, setParentForNew] = useState<string | null>(null); const [expanded, setExpanded] = useState<Set<string>>(() => new Set()); const [draggedId, setDraggedId] = useState<string | null>(null);
  const [creating, setCreating] = useState(false); const [menuId, setMenuId] = useState<string | null>(null);

  const load = useCallback(async () => { setLoading(true); setError(null); try { const suffix = projectId ? `?project=${projectId}` : ""; const [work, projectData, peopleData, settings] = await Promise.all([api<{ items: WorkItem[] }>(`/api/work-items${suffix}`), api<{ projects: Project[] }>("/api/projects"), api<{ people: Person[] }>("/api/people"), api<{ defaultProjectId: string | null }>("/api/planning-settings")]); setItems(work.items); setProjects(projectData.projects); setPeople(peopleData.people); setDefaultProjectId(settings.defaultProjectId); setExpanded((current) => current.size ? current : new Set(work.items.map((item) => item.id))); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Не удалось загрузить план"); } finally { setLoading(false); } }, [projectId]);
  useEffect(() => { const frame = requestAnimationFrame(() => { const initialProject = new URLSearchParams(window.location.search).get("project"); if (initialProject && !projectId) setProjectId(initialProject); else void load(); }); return () => cancelAnimationFrame(frame); }, [load, projectId]);

  const byParent = useMemo(() => { const map = new Map<string | null, WorkItem[]>(); for (const item of items) { const key = item.parentId && items.some((candidate) => candidate.id === item.parentId) ? item.parentId : null; map.set(key, [...(map.get(key) ?? []), item]); } return map; }, [items]);
  function toggle(id: string) { setExpanded((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }

  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); const data = new FormData(event.currentTarget); try { await api("/api/work-items", { method: "POST", body: JSON.stringify({ title: data.get("title"), description: data.get("description"), parentId: data.get("parentId") || null, projectIds: data.getAll("projectIds"), workflowStage: data.get("workflowStage"), assigneeId: data.get("assigneeId") || null, dueDate: data.get("dueDate") || null }) }); event.currentTarget.reset(); setParentForNew(null); setCreating(false); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Не удалось создать задачу"); } finally { setSaving(false); } }

  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editing) return; setSaving(true); const data = new FormData(event.currentTarget); try { await api(`/api/work-items/${editing.id}`, { method: "PATCH", body: JSON.stringify({ title: data.get("title"), description: data.get("description"), parentId: data.get("parentId") || null, projectIds: data.getAll("projectIds"), status: data.get("status"), workflowStage: data.get("workflowStage"), assigneeId: data.get("assigneeId") || null, dueDate: data.get("dueDate") || null, links: parseLinks(String(data.get("links") ?? "")) }) }); setEditing(null); await load(); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Не удалось обновить задачу"); } finally { setSaving(false); } }
  function parseLinks(value: string) { return value.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [label, ...url] = line.split("|"); return { label: (url.length ? label : "Source").trim(), url: (url.length ? url.join("|") : label).trim() }; }); }

  async function move(beforeId: string | null) { if (!draggedId || draggedId === beforeId) return; try { await api(`/api/work-items/${draggedId}`, { method: "PATCH", body: JSON.stringify({ beforeId }) }); setDraggedId(null); await load(); } catch (moveError) { setError(moveError instanceof Error ? moveError.message : "Не удалось изменить порядок"); } }
  async function changeDefault(value: string) { try { await api("/api/planning-settings", { method: "PATCH", body: JSON.stringify({ defaultProjectId: value }) }); setDefaultProjectId(value); } catch (settingError) { setError(settingError instanceof Error ? settingError.message : "Не удалось сохранить default project"); } }
  async function remove(item: WorkItem) { if (!confirm("Удалить Work Item? Дочерние задачи сначала нужно переместить.")) return; try { await api(`/api/work-items/${item.id}`, { method: "DELETE" }); await load(); } catch (deleteError) { setError(deleteError instanceof Error ? deleteError.message : "Не удалось удалить задачу"); } }

  const itemCard = (item: WorkItem, depth = 0) => { const children = byParent.get(item.id) ?? []; return <div key={item.id}>{<article className="work-item-card" style={{ marginLeft: view === "tree" ? Math.min(depth, 8) * 22 : 0 }} draggable={view === "backlog"} onDragStart={() => setDraggedId(item.id)} onDragOver={(event) => event.preventDefault()} onDrop={() => void move(item.id)}>
    {view === "tree" && <button className="tree-toggle" aria-label={expanded.has(item.id) ? "Свернуть" : "Развернуть"} onClick={() => toggle(item.id)}>{children.length ? expanded.has(item.id) ? "−" : "+" : "·"}</button>}
    {view === "backlog" && <span className="drag-handle" aria-hidden="true">⋮⋮</span>}
    <div className="work-item-main"><div className="work-item-title">{item.title}{item.sourceLogId && <span title="Создано из Task-log">↗ log</span>}</div><div className="work-item-meta"><span>Этап: {stages.find(([value]) => value === item.workflowStage)?.[1]}</span><span>Состояние: {item.status === "active" ? "Открыта" : item.status === "done" ? "Завершена" : "Отменена"}</span>{item.projects.map((project) => <span key={project.id}>#{project.slug}</span>)}{item.assigneeId && <span>@{people.find((person) => person.id === item.assigneeId)?.alias ?? "unknown"}</span>}{item.dueDate && <span>до {item.dueDate}</span>}</div>{item.description && <div className="work-item-description"><ReactMarkdown>{item.description}</ReactMarkdown></div>}{item.links.length > 0 && <div className="work-item-links">{item.links.map((link) => <a key={link.id ?? link.url} href={link.url} target="_blank" rel="noreferrer">↗ {link.label}</a>)}</div>}</div>
    <div className="work-item-menu-wrap"><button className="work-item-menu-trigger" aria-label="Действия с задачей" aria-haspopup="menu" aria-expanded={menuId === item.id} onClick={() => setMenuId((current) => current === item.id ? null : item.id)}>⋯</button>{menuId === item.id && <div className="record-menu work-item-menu" role="menu"><button role="menuitem" onClick={() => { setParentForNew(item.id); setCreating(true); setMenuId(null); }}>Добавить подзадачу</button><button role="menuitem" onClick={() => { setEditing(item); setMenuId(null); }}>Изменить</button><button role="menuitem" className="danger" onClick={() => { setMenuId(null); void remove(item); }}>Удалить</button></div>}</div>
  </article>}{view === "tree" && expanded.has(item.id) && children.map((child) => itemCard(child, depth + 1))}</div>; };

  return <>
    {error && <div className="error-banner" role="alert">{error}<button onClick={() => setError(null)}>×</button></div>}
    <section className="planning-toolbar"><div className="view-tabs" role="tablist"><button className={view === "tree" ? "active" : ""} onClick={() => setView("tree")}>Tree</button><button className={view === "backlog" ? "active" : ""} onClick={() => setView("backlog")}>Backlog</button></div><label>Проект<select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Все проекты</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label>Default project<select value={defaultProjectId ?? ""} onChange={(event) => void changeDefault(event.target.value)}><option value="">Не выбран</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label></section>
    <section className="planning-layout planning-layout-compact"><div className="work-items-panel"><div className="panel-heading"><div><p className="eyebrow">{view === "tree" ? "Decomposition" : "Execution order"}</p><h2>{view === "tree" ? "Дерево задач" : "Общий backlog"}</h2></div><span className="counter">{items.length}</span></div>{loading ? <div className="state-card">Загружаем задачи…</div> : items.length ? <div className="work-items-list" onDragOver={(event) => event.preventDefault()} onDrop={() => void move(null)}>{view === "tree" ? (byParent.get(null) ?? []).map((item) => itemCard(item)) : items.map((item) => itemCard(item))}</div> : <div className="state-card"><strong>Создайте первый Work Item</strong><p>Task-записи из журнала также будут появляться здесь автоматически.</p></div>}</div></section>
    <button className="floating-add" type="button" aria-label="Добавить Work Item" title="Добавить Work Item" onClick={() => { setParentForNew(null); setCreating(true); }}>+</button>
    {creating && <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) { setCreating(false); setParentForNew(null); } }}><section className="modal work-item-modal" role="dialog" aria-modal="true" aria-labelledby="create-work-item-title"><div className="modal-heading"><div><p className="eyebrow">{parentForNew ? "Новая подзадача" : "Новая задача"}</p><h2 id="create-work-item-title">Добавить Work Item</h2></div><button className="close-button" onClick={() => { setCreating(false); setParentForNew(null); }} aria-label="Закрыть">×</button></div><form onSubmit={create}><label>Название<input name="title" autoFocus required maxLength={500} /></label><label>Описание<textarea name="description" rows={5} /></label><label>Parent<select name="parentId" defaultValue={parentForNew ?? ""}><option value="">Top level</option>{items.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Проекты<select name="projectIds" multiple defaultValue={projectId ? [projectId] : defaultProjectId ? [defaultProjectId] : []}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><div className="composer-row"><label>Этап<select name="workflowStage" defaultValue="backlog">{stages.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Assignee<select name="assigneeId"><option value="">Не назначен</option>{people.map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select></label></div><label>Due date<input name="dueDate" type="date" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => { setCreating(false); setParentForNew(null); }}>Отмена</button><button className="primary-button" disabled={saving}>{saving ? "Сохраняем…" : "Добавить"}</button></div></form></section></div>}
    {editing && <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setEditing(null); }}><section className="modal work-item-modal" role="dialog" aria-modal="true"><div className="modal-heading"><div><p className="eyebrow">Work Item</p><h2>Редактирование</h2></div><button className="close-button" onClick={() => setEditing(null)}>×</button></div><form onSubmit={update}><label>Название<input name="title" required defaultValue={editing.title} /></label><label>Описание<textarea name="description" rows={6} defaultValue={editing.description} /></label><div className="composer-row"><label>Состояние<select name="status" defaultValue={editing.status}>{(["active","done","cancelled"] as WorkItemStatus[]).map((value) => <option key={value} value={value}>{value === "active" ? "Открыта" : value === "done" ? "Завершена" : "Отменена"}</option>)}</select></label><label>Этап<select name="workflowStage" defaultValue={editing.workflowStage}>{stages.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><label>Parent<select name="parentId" defaultValue={editing.parentId ?? ""}><option value="">Top level</option>{items.filter((item) => item.id !== editing.id).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Проекты<select name="projectIds" multiple defaultValue={editing.projects.map((project) => project.id)}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><div className="composer-row"><label>Assignee<select name="assigneeId" defaultValue={editing.assigneeId ?? ""}><option value="">Не назначен</option>{people.map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select></label><label>Due date<input name="dueDate" type="date" defaultValue={editing.dueDate ?? ""} /></label></div><label>External links <span className="field-hint">Одна строка: Label | https://…</span><textarea name="links" rows={4} defaultValue={editing.links.map((link) => `${link.label} | ${link.url}`).join("\n")} /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setEditing(null)}>Отмена</button><button className="primary-button" disabled={saving}>Сохранить</button></div></form></section></div>}
  </>;
}
