"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Suggestion = { id:string; batchId:string; batchTitle:string; sourceSystem:string; type:"decision"|"task"|"question"; content:string; description:string; status:"pending"|"processing"|"approved"|"rejected"; externalKey:string|null; externalUrl:string|null; canonicalLogId:string|null; createdAt:string };
async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,headers:{"content-type":"application/json",...init?.headers}});const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error??"Не удалось выполнить запрос");return data;}

export default function ImportsClient(){
  const [suggestions,setSuggestions]=useState<Suggestion[]>([]); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null); const [filter,setFilter]=useState<"pending"|"all">("pending");
  const load=useCallback(async()=>{try{const result=await api<{suggestions:Suggestion[]}>("/api/imports");setSuggestions(result.suggestions);}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить импорт");}},[]);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{void load();});return()=>cancelAnimationFrame(frame);},[load]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);setSaving(true);setError(null);try{const raw=String(data.get("content")??"").trim();let payload:unknown={title:data.get("title"),sourceSystem:data.get("sourceSystem"),text:raw};if(raw.startsWith("{")){payload=JSON.parse(raw);}else if(raw.startsWith("[")){payload={formatVersion:"1",title:data.get("title"),sourceSystem:data.get("sourceSystem"),suggestions:JSON.parse(raw)};}await api("/api/imports",{method:"POST",body:JSON.stringify(payload)});form.reset();setOpen(false);await load();}catch(e){setError(e instanceof Error?e.message:"Не удалось создать batch");}finally{setSaving(false);}}
  async function review(id:string,action:"approve"|"reject"){setError(null);try{await api(`/api/imports/${id}`,{method:"PATCH",body:JSON.stringify({action})});await load();}catch(e){setError(e instanceof Error?e.message:"Не удалось проверить предложение");}}
  const visible=useMemo(()=>filter==="pending"?suggestions.filter(item=>item.status==="pending"):suggestions,[filter,suggestions]);
  return <>
    <div className="import-toolbar"><div className="view-tabs" role="tablist"><button className={filter==="pending"?"active":""} onClick={()=>setFilter("pending")}>На проверке</button><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Все</button></div><span className="counter">{suggestions.filter(item=>item.status==="pending").length} ожидают решения</span></div>
    {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError(null)}>×</button></div>}
    <section className="import-list">{visible.length?visible.map(item=><article className={`import-suggestion ${item.type} ${item.status}`} key={item.id}><div className="suggestion-meta"><span>{item.type}</span><span>{item.sourceSystem}</span><span>{item.status==="pending"?"Предложение · требует проверки":item.status==="processing"?"Обрабатывается":item.status==="approved"?"Подтверждено":"Отклонено"}</span></div><h3>{item.content}</h3>{item.description&&<p>{item.description}</p>}{item.externalKey&&<code>{item.externalKey}</code>}{item.externalUrl&&<a href={item.externalUrl} target="_blank" rel="noreferrer">↗ источник</a>}{item.status==="pending"&&<div className="review-actions"><button className="reject-button" onClick={()=>void review(item.id,"reject")}>Нет</button><button className="approve-button" onClick={()=>void review(item.id,"approve")}>Да, добавить</button></div>}</article>):<div className="state-card"><strong>Нет предложений на проверке</strong><p>Импортируйте подготовленный batch — обычный журнал останется без изменений до подтверждения.</p></div>}</section>
    <button className="floating-add" onClick={()=>setOpen(true)} aria-label="Импортировать">+</button>
    {open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="modal import-modal" role="dialog" aria-modal="true" aria-labelledby="import-title"><div className="modal-heading"><div><p className="eyebrow">Reviewable import</p><h2 id="import-title">Новый batch</h2></div><button className="close-button" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={create}><label>Название<input name="title" defaultValue="Meeting import" required /></label><label>Источник<select name="sourceSystem" defaultValue="manual"><option value="manual">Manual / skill</option><option value="granola">Granola</option><option value="jira">Jira</option></select></label><label>Plain text или JSON v1 <span className="field-hint">Строки Decision:, Task:, Question: либо массив suggestions</span><textarea name="content" rows={12} required placeholder={'Decision: Объединить команды @core и @platform\nTask: Подготовить план #quotes\nQuestion: Кто отвечает за rollout?'} /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Отмена</button><button className="primary-button" disabled={saving}>{saving?"Импортируем…":"Создать предложения"}</button></div></form></section></div>}
  </>;
}
